export const FETCH_POSTS_SUCCESS='FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR='FETCH_POSTS_ERROR';
export const NEW_POST_SUCCESS='NEW_POST_SUCCESS';
export const NEW_POST_ERROR='NEW_POST_ERROR';
export const DELETE_POST_SUCCESS='DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR='DELETE_POST_ERROR';