export const FETCH_STOCKLOGSS_SUCCESS='FETCH_STOCKLOGSS_SUCCESS';
export const FETCH_STOCKLOGSS_ERROR='FETCH_STOCKLOGSS_ERROR';
export const NEW_STOCKLOGS_SUCCESS='NEW_STOCKLOGS_SUCCESS';
export const NEW_STOCKLOGS_ERROR='NEW_STOCKLOGS_ERROR';
export const DELETE_STOCKLOGS_SUCCESS='DELETE_STOCKLOGS_SUCCESS';
export const DELETE_STOCKLOGS_ERROR='DELETE_STOCKLOGS_ERROR';