export const FETCH_USERS_SUCCESS='FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR='FETCH_USERS_ERROR';
export const NEW_USER_SUCCESS= 'NEW_USER_SUCCESS';
export const NEW_USER_ERROR= 'NEW_USER_ERROR'; 
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR='DELETE_USER_ERROR';
export const CREATING_USER='CREATING_USER'

export const FETCH_DEPTS_SUCCESS='FETCH_DEPTS_SUCCESS';
export const FETCH_DEPTS_ERROR='FETCH_DEPTS_ERROR';
export const FETCH_DEPT_USERS_SUCCESS='FETCH_DEPT_USERS_SUCCESS';
export const FETCH_DEPT_USERS_ERROR='FETCH_DEPT_USERS_ERROR';
export const NEW_DEPT_SUCCESS='NEW_DEPT_SUCCESS';
export const NEW_DEPT_ERROR='NEW_DEPT_ERROR';
export const DELETE_DEPT_SUCCESS='DELETE_DEPT_SUCCESS';
export const DELETE_DEPT_ERROR='DELETE_DEPT_ERROR';

export const FETCH_ROLES_SUCCESS='FETCH_ROLES_SUCCESS';
export const FETCH_ROLES_ERROR='FETCH_ROLES_ERROR';
export const FETCH_ROLE_USERS_SUCCESS='FETCH_ROLE_USERS_SUCCESS';
export const FETCH_ROLE_USERS_ERROR='FETCH_ROLE_USERS_ERROR';
export const NEW_ROLE_SUCCESS='NEW_ROLE__SUCCESS';
export const NEW_ROLE_ERROR='NEW_ROLE_ERROR';

export const FETCH_SUPPLIERS_SUCCESS='FETCH_SUPPLIERS_SUCCESS';
export const FETCH_SUPPLIER_ERROR='FETCH_SUPPLIER_ERROR';
export const FETCH_SUPPLIER_SUCCESS='FETCH_SUPPLIER_SUCCESS';
export const FETCH_SUPPLIERS_ERROR='FETCH_SUPPLIERS_ERROR';
export const NEW_SUPPLIER_SUCCESS='NEW_SUPPLIER_SUCCESS';
export const NEW_SUPPLIER_ERROR='NEW_SUPPLIER_ERROR';

export const FETCH_PRODUCTS_SUCCESS='FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR='FETCH_PRODUCTS_ERROR';
export const NEW_PRODUCT_SUCCESS='NEW_PRODUCT_SUCCESS';
export const NEW_PRODUCT_ERROR='NEW_PRODUCT_ERROR';
export const DELETE_PRODUCT_SUCCESS='DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR='DELETE_PRODUCT_ERROR';

export const FETCH_PRODUCTCATEGS_SUCCESS='FETCH_PRODUCTCATEGS_SUCCESS';
export const FETCH_PRODUCTCATEGS_ERROR='FETCH_PRODUCTCATEGS_ERROR';
export const NEW_PRODUCTCATEG_SUCCESS='NEW_PRODUCTCATEG_SUCCESS';
export const NEW_PRODUCTCATEG_ERROR='NEW_PRODUCTCATEG_ERROR';
export const DELETE_PRODUCTCATEG_SUCCESS='DELETE_PRODUCTCATEG_SUCCESS';
export const DELETE_PRODUCTCATEG_ERROR='DELETE_PRODUCTCATEG_ERROR';

export const FETCH_STOCKPRODUCTS_SUCCESS='FETCH_STOCKPRODUCTS_SUCCESS';
export const FETCH_STOCKPRODUCTS_ERROR='FETCH_STOCKPRODUCTS_ERROR';
export const NEW_STOCKPRODUCT_SUCCESS='NEW_STOCKPRODUCT_SUCCESS';
export const NEW_STOCKPRODUCT_ERROR='NEW_STOCKPRODUCT_ERROR';
export const DELETE_STOCKPRODUCT_SUCCESS='DELETE_STOCKPRODUCT_SUCCESS';
export const DELETE_STOCKPRODUCT_ERROR='DELETE_STOCKPRODUCT_ERROR';

export const FETCH_STOCKLOGS_SUCCESS='FETCH_STOCKLOGSS_SUCCESS';
export const FETCH_STOCKLOGS_ERROR='FETCH_STOCKLOGSS_ERROR';
export const NEW_STOCKLOG_SUCCESS='NEW_STOCKLOG_SUCCESS';
export const NEW_STOCKLOG_ERROR='NEW_STOCKLOG_ERROR';
export const DELETE_STOCKLOG_SUCCESS='DELETE_STOCKLOG_SUCCESS';
export const DELETE_STOCKLOG_ERROR='DELETE_STOCKLOG_ERROR';
export const UPDATE_STATUS_STOCKLOG_ERROR='UPDATE_STATUS_STOCKLOG_ERROR';
export const UPDATE_STATUS_STOCKLOG_SUCCESS='UPDATE_STATUS_STOCKLOG_SUCCESS';

export const FETCH_REQUESTS_SUCCESS='FETCH_REQUESTS_SUCCESS';
export const FETCH_REQUESTS_ERROR='FETCH_REQUESTS_ERROR';
export const NEW_REQUEST_SUCCESS='NEW_REQUEST_SUCCESS';
export const NEW_REQUEST_ERROR='NEW_REQUEST_ERROR';
export const DELETE_REQUEST_SUCCESS='DELETE_REQUEST_SUCCESS';
export const DELETE_REQUEST_ERROR='DELETE_REQUEST_ERROR';

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";